    --[[
        Want a new language added to the script with full credit given in the description?
        Copy the table and fill it out with a non Google Translated translation.
        Feel free to add me on Steam; http://steamcommunity.com/id/tedlua/ or message me on GModStore.

        Please use the main config file to select between the support languages.
        Only edit this if you want to create a language on your own. I will not help you if you break something in here.
        Thanks.
    ]]

    Executioner.Config.Language[ 'english' ] = {
        HitPriceFormatError = 'There is something wrong with the hit price. Maximum %s - Minimum %s.',
        HitPriceCantAfford = 'You can not afford to place this hit as it costs %s and you currently have %s.',
        BonusWeaponAccepted = 'The %s will be removed once the hit has been attempted.',
        HitTimeReached = '%s has run out of time to complete their hit. The hit has failed!',
        HitTooSoon = 'You can not place a hit so soon.',
        HitmanBusy = '%s is already dealing with someone.',
        RequestSent = 'Your hit request has been sent to %s.',
        CustomerNoResponse = '%s has not responded to your request.',
        HitmanNoResponse = 'You failed to respond to the hit request in time.',
        TargetRejectHit = 'You can not place a hit on this person.',
        InvalidTargets = 'Could not place hit. Client(s) are not connected to the server, or you are dead.',
        CustomerOnHitAccepted = '%s has accepted your hit request against %s. The money has now been taken.',
        CustomerOnHitDeclined = '%s has declined your hit request. You have not been charged.',
        HitmanOnHitAccepted = 'You have accepted %s\'s hit offer against %s for %s.',
        HitmanOnHitDeclined = 'You have declined %s\'s hit.',
        MessageAllOnAccepted = 'Someone has accepted a hit. Watch out, you might be the target.',
        BonusWeaponHitComplete = '%s completed the hit using the %s against %s. They have been rewarded with %s and a bonus of %s.',
        HitCompletedNoBonus = '%s completed their hit against %s and has been rewarded with %s.',
        TaxOnKill = 'Your overall income has been taxed by ' .. Executioner.Config.TaxOnKill .. '%.',
        TargetDiedBeforeHit = '%s\'s target %s was killed before they could complete their hit. The hit has failed!',
        TargetKilledHitman = '%s was no match for their target %s. They have been killed. The hit has failed!',
        HitmanDied = 'Hitman %s was killed before they had a chance to complete their hit. The hit has failed!',
        TargetDisconnected = 'Target %s has left the server with an active hit. The customer has been refunded.',
        HitmanDisconnected = 'Hitman %s has left the server. The hit has been refunded.',
        CustomerDisconnected = 'Customer %s has left the server. The hit has been removed.',
        HitmanChangedJob = 'Hitman %s has changed job. The hit has been refunded and the customer has been given %s back.', -- REMOVE
        HitmanArrested = 'Hitman %s has been arrested by %s. The hit has been refunded.',
        TargetArrested = 'Target %s has been arrested by %s. The hit has been refunded.',
        PhoneNoSave = 'There is nothing to save.',
        PhoneOnSave = '%i Phone(s) have been saved successfully.',
        PhoneOnReset = 'Successfully removed %i phones and reset all data.',
        OnSwitchTeam = '%s has changed to a %s the Hit has been refunded.',
        BonusNoReply = 'You took too long to reply to the Bonus Weapon offer.',
        HitActive = 'This person is apart of a Hit transaction already. You can not place a Hit on them.',
        SameTargetTooSoon = 'This person has recently had a Hit made against them, you can not place one on this person just yet.',
        CantDrop = 'You can not drop a Bonus Weapon.',
        --> Start of Phone Related Messages <--
        OnRandomHit = 'Anonymous has placed a hit on a suspect. More detail is displayed on your phone. Type ' .. Executioner.Config.Phone_Command .. '.',
        OnRadomHitAccepted = 'You have accepted a randomly generated hit against %s for %s.',
        HitmanActiveHit = 'You already have an active hit. There\'s no need to take another one.',
        NotEnoughHitmen = 'There isn\'t enough Hitmen connected to the server right now. You can not place a Hit.',
        CustomerOnPhoneHitPlaced = 'You have made a hit against %s. Hitmen will deal with this request soon. You have been charged %s.',
        HitmanNotifyRequest = '%s has requested for a hit to be carried out. More detail is displayed on your phone. Type ' .. Executioner.Config.Phone_Command .. '.',
        PhoneNotInService = 'The phone is not in service right now, come back later.',
        HitmanOnUsePhone = 'You can not use the Phone as a Hitman.'
    }

    Executioner.Config.Language[ 'norwegian' ] = {
        HitPriceFormatError = 'Det er noe galt med hit prisen. Maks %s - Minst %s.',
        HitPriceCantAfford = 'Du har ikke råd til å å sette hit i og med at det koster %s og for øyeblikket har du %s.',
        BonusWeaponAccepted = '%s vil bli borte når mordet har blitt forsøkt.',
        HitTimeReached = '%s har gått tom for tid for å fullføre deres hit. Mordet var mislykket!',
        HitTooSoon = 'Du kan ikke allerede plassere et nytt hit.',
        HitmanBusy = '%s jobber allerede med noen.',
        RequestSent = 'Din forespørsel er sendt til %s.',
        CustomerNoResponse = '%s har ikke svart på din forespørsel.',
        HitmanNoResponse = 'Du klarte ikke å svare på forespørselen i tide.',
        TargetRejectHit = 'Du kan ikke plassere et hit på denne personen.',
        InvalidTargets = 'Kunne ikke plassere et hit. Kunden(e) er ikke koblet til serveren, eller så er du død.',
        CustomerOnHitAccepted = '%s har akseptert ditt hit-forespørsel på %s. Pengene har nå blitt overført.',
        CustomerOnHitDeclined = '%s har avvist ditt hit-forespørsel. Du har ikke blitt belastet.',
        HitmanOnHitAccepted = 'Du har akseptert %s\'s hit-forespørsel mot %s for %s.',
        HitmanOnHitDeclined = 'Du har avvist %s\'s hit.',
        MessageAllOnAccepted = 'Noen har akseptert et hit. Se deg for, du er kanskje neste mål.',
        BonusWeaponHitComplete = '%s har fullført et hit ved bruk av %s mot %s. De har blitt belønnet med %s og et bonus av %s.',
        HitCompletedNoBonus = '%s har fullført deres hit på %s og har blitt belønnet med %s.',
        TaxOnKill = 'Din samlede inntekt har blitt skattelagt av ' .. Executioner.Config.TaxOnKill .. '%.',
        TargetDiedBeforeHit = '%s\'s mål %s ble drept før de kunne fullføre deres hit. Hit-forespørselet som ble satt, mislyktes!',
        TargetKilledHitman = '%s slo %s i sitt eget spill. Leiemorderen har blitt drept. Mordet mislyktes!',
        HitmanDied = 'Leiemorder %s ble drept før han/hun hadde muligheten til å fullføre deres hit. Hit-forespørselen var misslykket!',
        TargetDisconnected = 'Målet %s forlot serveren med et aktiv hit. Kunden har blitt betalt tilbake.',
        HitmanDisconnected = 'Leiemorder %s har forlatt serveren. Hit-forespørselen er tatt tilbake.',
        CustomerDisconnected = 'Kunden %s har forlatt serveren. Hit-forespørselen er tatt tilbake.',
        HitmanChangedJob = 'Leiemorder %s har byttet jobb. Hit-forespørselen har blitt refundert og kunden har fått %s tilbake.',
        HitmanArrested = 'Leiemorder %s har blitt arrestert av %s. Hit-forespørselen har blitt refundert.',
        TargetArrested = 'Målet %s har blitt arrestert av %s. Hit-forespørselen har blitt refundert.',
        PhoneNoSave = 'Det er ingenting å lagre.',
        PhoneOnSave = '%i Telefon(er) har blitt lagret.',
        PhoneOnReset = 'Telefonene til %i ble vellykket fjernet og alle dataene er tilbakestilt',
        OnSwitchTeam = '%s har endret seg til %s hvis Hit er refundert.',
        BonusNoReply = 'Du tok for lang tid til å svare på bonustilbudet',
        HitActive = 'Denne personen er allerede fra en Hit-transaksjon. Du kan ikke plassere et slag på dem.',
        SameTargetTooSoon = 'Denne personen har nylig hatt et Hit mot dem, du kan ikke plassere en på denne personen ennå.',
        CantDrop = 'Du kan ikke slippe en bonusvåpen.',
        --> Starten på telefon relatert meldinger <--
        OnRandomHit = 'Det har blitt plassert et hit anonymt på en mistenkt. Flere detaljer er vist på telefonen. Skriv ' .. Executioner.Config.Phone_Command .. '.',
        OnRadomHitAccepted = 'Du har akseptert et tilfeldig generert hit på %s for %s.',
        HitmanActiveHit = 'Du har allerede et aktivt hit. Det er ikke nødvendig med en til.',
        NotEnoughHitmen = 'Det er ikke nok leiemordere på serveren for øyeblikket. Du kan ikke plassere et hit.',
        CustomerOnPhoneHitPlaced = 'Du har satt et hit på %s. Leiemordere vil ta hånd om ditt forespørsel snart. Du har blitt belastet %s.',
        HitmanNotifyRequest = '%s har bedt om at et hit skal utføres. Flere detaljer vises på telefonen. Skriv ' .. Executioner.Config.Phone_Command .. '.',
        PhoneNotInService = 'Telefonen er ikke i tjeneste for øyeblikket, kom tilbake senere.',
        HitmanOnUsePhone = 'Du kan ikke bruke telefonen som en leiemorder. Skriv ' .. Executioner.Config.Phone_Command .. ' istedet.'
    }

    Executioner.Config.Language[ 'dutch' ] = {
        HitPriceFormatError = 'Er is iets fout met de kosten van de hit. Maximaal %s - Minimaal %s.',
        HitPriceCantAfford = 'Je hebt niet genoeg geld voor deze hit. Het kost %s, je hebt op dit moment %s.',
        BonusWeaponAccepted = 'Het %s zal weggehaald worden wanneer een poging is gedaan tot de hit.',
        HitTimeReached = '%s heeft geen tijd meer om de hit te voltooien. De hit was niet geslaagd!',
        HitTooSoon = 'Je kunt de hit niet zo vroeg plaatsen.',
        HitmanBusy = '%s is al bezig met iemand.',
        RequestSent = 'Je hit verzoek is verstuurd naar %s.',
        CustomerNoResponse = '%s heeft niet geantwoord op je verzoek.',
        HitmanNoResponse = 'Je was te laat om het hit verzoek te beantwoorden.',
        TargetRejectHit = 'Je kan geen hit plaatsen op dit persoon.',
        InvalidTargets = 'Kon de hit niet plaatsen. Client(en) zijn niet verbonden met de server, of je bent dood.',
        CustomerOnHitAccepted = 'Je hebt %s\'s hit verzoek op %s voor %s geaccepteerd.',
        CustomerOnHitDeclined = '%s heeft je hit geweigerd. Je hebt niets hoeven betalen.',
        HitmanOnHitAccepted = 'Je hebt geaccepteerd %s\'s hit verzoek op %s voor %s.',
        HitmanOnHitDeclined = 'Je hebt %s\'s hit geweigerd.',
        MessageAllOnAccepted = 'Iemand heeft je hit geaccepteerd. Kijk uit, jij zou het doelwit kunnen zijn.',
        BonusWeaponHitComplete = '%s heeft de hit volbracht met %s op %s. Ze zijn beloond met %s en een bonus van %s.',
        HitCompletedNoBonus = '%s heeft zijn hit op %s volbracht en is beloond met %s.',
        TaxOnKill = 'Je totale inkomen is belast met ' .. Executioner.Config.TaxOnKill .. '%.',
        TargetDiedBeforeHit = '%s\'s doelwit %s was vermoord voordat ze de hit konden voltooien. De hit is gefaald!',
        TargetKilledHitman = '%s was geen match voor hun doelwit %s. Ze zijn vermoord. De hit is gefaald!',
        HitmanDied = 'Hitman %s was vermoord voordat ze een kans hadden om hun hit te voltooien. De hit is gefaald!',
        TargetDisconnected = 'Doelwit %s heeft de server verlaten met een active hit. De klant is terugbetaald.',
        HitmanDisconnected = 'Hitman %s heeft de server verlaten. De hit is terugbetaald.',
        CustomerDisconnected = 'Klant %s heeft de server verlaten. De hit is terugbetaald.',
        HitmanChangedJob = 'Hitman %s heeft zijn klasse veranderd. De hit is terugbetaald en aan de klant is %s terug gegeven.',
        HitmanArrested = 'Hitman %s is gearresteerd door %s. De hit is terugbetaald.',
        TargetArrested = 'Target %s is gearresteerd door %s. De hit is terugbetaald.',
        PhoneNoSave = 'Er is niets om te redden.',
        PhoneOnSave = '%i Telefoon(s) zijn succesvol opgeslagen.',
        PhoneOnReset = 'Succesvol verwijderd %i phones en reset alle gegevens.',
        OnSwitchTeam = '%s is veranderd in een %s the Hit is terugbetaald.',
        BonusNoReply = 'Je hebt te lang geduurd om te antwoorden op de bonusaanbieding',
        HitActive = 'Deze persoon maakt al deel uit van een Hit-transactie. Je kunt geen Hit op hem plaatsen.',
        SameTargetTooSoon = 'Deze persoon heeft recent een klap tegen zich gekregen, je kunt er nog geen één op deze persoon plaatsen.',
        CantDrop = 'Je kunt een bonuswapen niet laten vallen.',
        --> Start of Phone Related Messages <--
        OnRandomHit = 'Anoniem heeft een hit op de verdachte geplaatst. Meer details zijn zichtbaar op je telefoon. Typ ' .. Executioner.Config.Phone_Command .. '.',
        OnRadomHitAccepted = 'Je hebt een willekeurig gegenereerde hit geaccepteerd op %s voor %s.',
        HitmanActiveHit = 'Je hebt al een actieve hit. Het is niet nodig er nog een te plaatsen.',
        NotEnoughHitmen = 'Er zijn niet genoeg hitmans verbonden met de server op het moment. Je kunt geen hit plaatsen',
        CustomerOnPhoneHitPlaced = 'Je hebt een hit gecreerd op %s. Hitmen zullen je verzoek spoedig behandelen. Je hebt betaald',
        HitmanNotifyRequest = '%s heeft verzocht een hit uit te voeren. Meer details zijn zichtbaar op je telefoon. Typ ' .. Executioner.Config.Phone_Command .. '.',
        PhoneNotInService = 'De telefoon is niet beschikbaar op dit moment, kom later terug.',
        HitmanOnUsePhone = 'Je kunt de telefoon niet als Hitman gebruiken. Typ ' .. Executioner.Config.Phone_Command .. ' inplaats daarvan.'
    }

	Executioner.Config.Language[ 'spanish' ] = {
        HitPriceFormatError = 'Hay un problema con el precio del hit. Máximo %s - Mínimo %s.',
        HitPriceCantAfford = 'No tienes dinero para comprar un hit, ya que este cuesta %s y tu solo tienes %s.',
        BonusWeaponAccepted = 'Los %s seran retirados una vez el hit proceda.',
        HitTimeReached = '%s se le ha terminado el  tiempo del hit. El hit no fue realizado!',
        HitTooSoon = 'No puedes hacer un hit tan pronto.',
        HitmanBusy = '%s ya está lidiando con alguien.',
        RequestSent = 'Tu pedido de hit se ha enviado a %s.',
        CustomerNoResponse = '%s no ha respondido a tu propuesta.',
        HitmanNoResponse = 'No has respondido el hit a tiempo.',
        TargetRejectHit = 'No puedes poner un hit a esta persona.',
        InvalidTargets = 'No se ha podido enviar el hit. El cliente no está en el servidor o tu estás muerto.',
        CustomerOnHitAccepted = '%s ha aceptado la solicitud de hit para %s. El dinero ha sido tomado.',
        CustomerOnHitDeclined = '%s ha denegado la solicitud de hit. El dinero se te ha devuelto.',
        HitmanOnHitAccepted = 'Has aceptado la solicitud de hit de %s\'s hacia %s por %s.',
        HitmanOnHitDeclined = 'Has denegado el hit de %s.',
        MessageAllOnAccepted = 'Alguien ha aceptado un hit. Ten cuidado, tu podrías ser el siguiente.',
        BonusWeaponHitComplete = '%s ha completado el hit con %s hacia %s. Se le ha recompensado con %s y un bonus de %s.',
        HitCompletedNoBonus = '%s ha completado el hit en contra de %s y se le ha recompensado con %s.',
        TaxOnKill = 'Tu ganancia ha recibido un impuesto de un ' .. Executioner.Config.TaxOnKill .. '%.',
        TargetDiedBeforeHit = 'El hit de %s (%s) ha muerto antes de que se completara el contrato. El sicario ha fallado!',
        TargetKilledHitman = '%s no ha podido contra %s. Ha sido asesinado. El sicario ha fallado!',
        HitmanDied = 'El sicario %s ha muerto antes de completar el contraro. El sicario ha fallado!',
        TargetDisconnected = 'La víctima %s ha dejado el servidor con un hit activo. Se ha devuelto el dinero del cliente.',
        HitmanDisconnected = 'El sicario %s ha dejado el servidor. Se ha devuelto el dinero del cliente.',
        CustomerDisconnected = 'El cliente %s ha dejado el servidor. El hit se ha cancelado.',
        HitmanChangedJob = 'El sicario %s cambió de trabajo. El hit se ha cancelado y se ha devuelto %s.', -- REMOVE
        HitmanArrested = 'El sicario %s ha sido arrestado por %s. El hit se ha devuelto.',
        TargetArrested = 'La víctima %s ha sido arrestada por %s. El hit se ha devuelto.',
        PhoneNoSave = 'No hay nada que guardar.',
        PhoneOnSave = '%i El teléfono se ha guardado correctamente.',
        PhoneOnReset = 'Se removieron %i telefonos y se reinicio toda la informacion.',
        OnSwitchTeam = '%s ha cambiado a %s El hit se ha devuelto.',
        BonusNoReply = 'Tardaste mucho en responder a la oferta de arma bonus.',
        HitActive = 'Esta persona ya forma parte de un contrato de Hit. No puedes poner un hit en el.',
        SameTargetTooSoon = 'Esta persona ha tenido recientemente un Hit en su contra, no puedes hacer un contrato contra el todavía.',
        CantDrop = 'No puedes soltar una arma de bonificacion.',
        --> Start of Phone Related Messages <--
        OnRandomHit = 'Un anonimo ha puesto un hit en un sospechoso. Mas detalles en tu telefono. Escribe ' .. Executioner.Config.Phone_Command .. '.',
        OnRadomHitAccepted = 'Aceptaste un hit generado aleatoriamente en contra de%s por %s.',
        HitmanActiveHit = 'Ya aceptaste un hit. No necesitas aceptar otro.',
        NotEnoughHitmen = 'No hay suficientes sicarios conectados actualment. No puedes colocar un hit.',
        CustomerOnPhoneHitPlaced = 'Has colocado un hit en contra de %s. Los sicarios se encargaran de su solicitud. Se le ha cobrado %s.',
        HitmanNotifyRequest = '%s ha solicitado que se ponga a dormir a alguien. Mas detalles en tu telefono. Escribe ' .. Executioner.Config.Phone_Command .. '.',
        PhoneNotInService = 'El telefono no esta funcionando ahora mismo, vuelve mas tarde.',
        HitmanOnUsePhone = 'No puedes usar el telefono como un Sicario.'
    }

    Executioner.Language = Executioner.Config.Language[ Executioner.Config.Language.Choice ]
