    --[[
        Executioner Logging Support;
        Huge thanks to Billy for allowing me to have a free copy of bLogs.
        Please do not edit this file.
    --]]

    ------------------------------
    --> Start of bLogs Support <--
    ------------------------------

    function Executioner.HandleBLogs()
        if bLogs and SERVER then
            local m = bLogs:Module()
            m.Category = 'General'
            m.Name = 'Executioner'
            m.Colour = Color( 230, 32, 25 )
            m:Hook( 'Executioner.OnHitAccepted', 'Executioner.Log.Accept', function( data )
                m:Log( bLogs:FormatPlayer( data.hitman ) .. ' has accepted a hit against ' .. bLogs:FormatPlayer( data.target ) .. ' for ' .. DarkRP.formatMoney( data.price ) .. '.' )
            end )
            m:Hook( 'Executioner.OnHitDeclined', 'Executioner.Log.Decline', function( data )
                m:Log( bLogs:FormatPlayer( data.hitman ) .. ' has declined a hit against ' .. bLogs:FormatPlayer( data.target ) .. ' for ' .. DarkRP.formatMoney( data.price ) .. '.' )
            end )
            m:Hook( 'Executioner.OnHitCompleted', 'Executioner.Log.Completed', function( data, victim, attacker, bonus )
                m:Log( bLogs:FormatPlayer( data.hitman ) .. ' has completed a hit against ' .. bLogs:FormatPlayer( data.target ) .. ' for ' .. DarkRP.formatMoney( data.price ) .. '.' )
            end )
            m:Hook( 'Executioner.OnHitFailed', 'Executioner.Log.Failed', function( data, victim, attacker, bonus )
                m:Log( bLogs:FormatPlayer( victim ) .. ' was killed. The hit has failed!' )
            end )
            m:Hook( 'Executioner.OnHitDisconnected', 'Executioner.Log.Disconnected', function( data, self )
                m:Log( 'Someone with a hit left the server. ' .. bLogs:FormatPlayer( data.hitman ) .. '\'s hit has failed!' )
            end )
            m:Hook( 'Executioner.OnHitArrested', 'Executioner.Log.Arrested', function( data, target, time, arrestor )
                m:Log( bLogs:FormatPlayer( target ) .. ' has been arrested by ' .. bLogs:FormatPlayer( arrestor ) .. '. The hit has failed!' )
            end )
            m:Hook( 'Executioner.OnHitExpired', 'Executioner.Log.Expired', function( data, reason )
                m:Log( reason )
            end )
            bLogs:AddModule( m )
        end
    end
    hook.Add( 'bLogs_FullyLoaded', 'Executioner.Handle.BLogs', Executioner.HandleBLogs )

    ------------------------------
